# Generated by Django 5.0.14 on 2026-08-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
